apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.sherpavad'
version = '0.1.0'

android {
  namespace 'expo.modules.sherpavad'
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
}

evaluationDependsOn(':react-native-sherpa-onnx')

def sherpaOnnxProject = project(':react-native-sherpa-onnx')
def sherpaOnnxClassesDir = file("${sherpaOnnxProject.buildDir}/sherpa-onnx-classes")

dependencies {
  implementation sherpaOnnxProject
  implementation fileTree(dir: sherpaOnnxClassesDir, include: '*.jar')
    .builtBy(sherpaOnnxProject.tasks.named('extractSherpaOnnxClasses'))
}
